export const ERROR_MSG_EMPTY_DATE = '* Ingrese una fecha';
export const ERROR_MSG_EMPTY_EMAIL = '* Ingrese un correo electrónico';
export const ERROR_MSG_EMPTY_NAME = '* Ingrese un nombre';
export const ERROR_MSG_EMPTY_PASSWORD = '* Ingrese una contraseña';
export const ERROR_MSG_EMPTY_REPEAT_PASSWORD = '* Ingrese la contraseña nuevamente';
export const ERROR_MSG_EMPTY_SURNAME = '* Ingrese un apellido';
export const ERROR_MSG_EXISTING_EMAIL = '* El email ingresado ya se encuentra en el sistema';
export const ERROR_MSG_INVALID_AGE = '* Debe ser mayor de 18 años';
export const ERROR_MSG_INVALID_DATE = '* La fecha ingresada en inválida';
export const ERROR_MSG_INVALID_EMAIL = '* El correo electrónico posee un formato inválido';
export const ERROR_MSG_INVALID_NAME = '* El nombre debe poseer solo caracteres alfabéticos';
export const ERROR_MSG_INVALID_PASSWORD_NO_CAPITAL_LETTERS = '* La contraseña no posee letras mayúsculas';
export const ERROR_MSG_INVALID_PASSWORD_NO_LOWER_CASE = '* La contraseña no posee letras minúsculas';
export const ERROR_MSG_INVALID_PASSWORD_NO_MIN_CHARACTERS = '* La contraseña debe tener mas de 6 caracteres';
export const ERROR_MSG_INVALID_PASSWORD_NO_NUMBERS = '* La contraseña no posee números'
export const ERROR_MSG_INVALID_SURNAME = '* El apellido debe poseer solo caracteres alfabéticos';
export const ERROR_MSG_PASSWORD_NO_MATCH = '* Las contraseñas no coinciden';
