module.exports = {
    EXPIRY_TIME: '2h',
    ADMIN_ROLE: 1,
    DRIVER_ROLE: 2,
    PASSENGER_ROLE: 3,
    NO_ACTIVE: 0,
    ACTIVE: 1,
    TICKET_PENDING_STATUS: 1,
    TICKET_ON_TRACK_STATUS: 2,
    TICKET_REJECT_STATUS: 3,
    TICKET_ABSENT_STATUS: 4,
    TICKET_FINISH_STATUS: 5
};
